<?php

return [
	'inp' => [
		'title'              => 'INP',
		'slug'               => 'inp',
		'status'             => 'publish',
		'core_area'          => 'Technisches Fundament',
		'index_policy'       => 'index',
		'excerpt'            => 'INP misst, wie schnell eine Seite auf echte Nutzerinteraktionen reagiert.',
		'short_definition'   => 'INP steht fuer Interaction to Next Paint. Die Metrik beschreibt, wie schnell eine Seite nach einer Eingabe sichtbar reagiert.',
		'why_it_matters'     => 'Ein guter INP sorgt dafuer, dass Formulare, Navigationen und CTA-Klicks nicht trage wirken. Schlechte Reaktionszeiten zerstoeren Vertrauen genau an den Stellen, an denen Nachfrage konkret wird.',
		'measurement'        => 'Relevant ist die Interaktion echter Nutzer. Besonders kritisch sind Menues, Filter, Formulare, Slider und alles, was nach einem Klick sichtbare Rueckmeldung geben muss.',
		'benchmarks'         => [
			[ 'label' => 'Gut', 'value' => 'bis 200 ms', 'note' => 'Interaktionen fuehlen sich direkt an.' ],
			[ 'label' => 'Optimieren', 'value' => '200 bis 500 ms', 'note' => 'Verzoegerungen werden wahrnehmbar.' ],
			[ 'label' => 'Schlecht', 'value' => 'ueber 500 ms', 'note' => 'Die Seite wirkt traege und unzuverlaessig.' ],
		],
		'mistakes'           => [
			'JavaScript-Last und UI-Logik wachsen, ohne dass Interaktionen unter echter Last getestet werden.',
			'Teams optimieren nur Ladezeit, obwohl Formulare, Menues oder Filter danach weiterhin langsam reagieren.',
			'Tracking-, Consent- oder Theme-Skripte blockieren den Main Thread genau in kaufnahen Momenten.',
		],
		'wgos_context'       => [
			'Im WGOS-Kontext ist INP kein Technik-Selbstzweck. Die Metrik entscheidet mit darueber, ob Nutzer ueberhaupt den naechsten sinnvollen Schritt gehen.',
			'Deshalb stuetzt ein sauberer INP sowohl die Core-Web-Vitals-Cluster-Seite als auch die Performance-Analyse als Lead-Magnet.',
		],
		'primary_url_key'    => 'cwv',
		'primary_url_label'  => 'Core Web Vitals',
		'primary_url_reason' => 'Der Head Term bleibt auf der Cluster-Seite. Das Glossar erklaert nur die Metrik darunter.',
		'related_primary_urls' => [
			[
				'key'    => 'cwv',
				'label'  => 'Core Web Vitals Cluster',
				'reason' => 'Ordnet INP in das Gesamtbild aus Performance, Nutzererlebnis und Priorisierung ein.',
			],
			[
				'key'    => 'performance_analysis',
				'label'  => 'Website Performance Analyse',
				'reason' => 'Fuehrt vom Begriff direkt in einen konkreten Performance-Check.',
			],
		],
		'related_assets'     => [
			'cwv-speed-audit' => 'Wenn INP auffaellig ist, bringt dieses Asset die technische Diagnose auf eine priorisierbare Ebene.',
		],
		'related_terms'      => [ 'lcp', 'cls', 'ttfb' ],
		'seo_title'          => 'INP: Definition, gute Werte und typische Bremsen | Haşim Üner',
		'seo_description'    => 'INP einfach erklaert: Was Interaction to Next Paint misst, welche Werte kritisch werden und wie der Begriff sauber auf Core Web Vitals und Performance-Checks verweist.',
	],
	'lcp' => [
		'title'            => 'LCP',
		'slug'             => 'lcp',
		'status'           => 'publish',
		'core_area'        => 'Technisches Fundament',
		'index_policy'     => 'index',
		'excerpt'          => 'LCP misst, wann das groesste sichtbare Element im Viewport geladen ist.',
		'short_definition' => 'LCP steht fuer Largest Contentful Paint. Die Metrik zeigt, wann der Hauptinhalt fuer Nutzer sichtbar genug geladen ist.',
		'why_it_matters'   => 'Wenn der wichtigste Inhalt zu spaet erscheint, wirkt die Seite langsam und der erste Eindruck kippt, noch bevor Nutzer ueberhaupt weiterlesen oder klicken.',
		'measurement'      => 'Relevant sind besonders Hero-Bilder, grosse Headline-Bloecke, Videos oder andere dominante Above-the-Fold-Elemente.',
		'benchmarks'       => [
			[ 'label' => 'Gut', 'value' => 'bis 2,5 s', 'note' => 'Der Hauptinhalt erscheint frueh und klar.' ],
			[ 'label' => 'Optimieren', 'value' => '2,5 bis 4,0 s', 'note' => 'Nutzer warten bereits spuerbar.' ],
			[ 'label' => 'Schlecht', 'value' => 'ueber 4,0 s', 'note' => 'Der Seitenstart fuehlt sich zu schwer und zu langsam an.' ],
		],
		'mistakes'         => [
			'Schwere Hero-Bilder oder Slider dominieren den sichtbaren Bereich ohne technische Begrenzung.',
			'Server, Fonts und Render-Blocking-Ressourcen werden getrennt betrachtet, obwohl sie denselben Effekt auf den Seitenstart haben.',
			'Teams optimieren nur Lab-Tests, aber nicht die reale Startwahrnehmung auf mobilen Verbindungen.',
		],
		'wgos_context'     => [
			'LCP ist im WGOS-Fundament ein Fruehsignal: Wenn der erste Eindruck nicht stimmt, bremsen spaetere SEO- oder CRO-Massnahmen direkt mit.',
			'Das Glossar liefert die Definition. Die Cluster- und Tool-Seiten uebernehmen Einordnung, Audit und naechsten Schritt.',
		],
		'primary_url_key'  => 'cwv',
		'primary_url_label'=> 'Core Web Vitals',
		'primary_url_reason' => 'LCP ist ein definitorischer Sub-Term unter dem Core-Web-Vitals-Cluster.',
		'related_primary_urls' => [
			[
				'key'    => 'cwv',
				'label'  => 'Core Web Vitals Cluster',
				'reason' => 'Fuehrt von der Einzelmetrik zur strategischen Einordnung.',
			],
			[
				'key'    => 'performance_analysis',
				'label'  => 'Website Performance Analyse',
				'reason' => 'Erlaubt den direkten Sprung von der Definition in einen auditierbaren Check.',
			],
		],
		'related_assets'   => [
			'cwv-speed-audit' => 'Zeigt, welche Bilder, Render-Blocker oder Server-Themen den LCP wirklich treiben.',
		],
		'related_terms'    => [ 'inp', 'cls', 'ttfb' ],
		'seo_title'        => 'LCP: Definition, gute Werte und typische Bremsen | Haşim Üner',
		'seo_description'  => 'LCP erklaert: Was Largest Contentful Paint bedeutet, welche Werte als gut gelten und wie die Metrik auf Core Web Vitals und Performance-Checks einzahlt.',
	],
	'cls' => [
		'title'            => 'CLS',
		'slug'             => 'cls',
		'status'           => 'publish',
		'core_area'        => 'Technisches Fundament',
		'index_policy'     => 'index',
		'excerpt'          => 'CLS misst, wie stark sich sichtbare Elemente waehrend des Ladens unerwartet verschieben.',
		'short_definition' => 'CLS steht fuer Cumulative Layout Shift. Die Metrik erfasst visuelle Instabilitaet waehrend des Seitenaufbaus.',
		'why_it_matters'   => 'Springende Layouts erzeugen Misstrauen. Nutzer klicken daneben, verlieren Kontext und erleben die Seite als unkontrolliert.',
		'measurement'      => 'Typische Ausloeser sind Bilder ohne reservierten Platz, spaet ladende Banner, Font-Wechsel und dynamische Module ueber dem aktuellen Fokus.',
		'benchmarks'       => [
			[ 'label' => 'Gut', 'value' => 'bis 0,1', 'note' => 'Die Seite bleibt visuell stabil.' ],
			[ 'label' => 'Optimieren', 'value' => '0,1 bis 0,25', 'note' => 'Verschiebungen sind schon wahrnehmbar.' ],
			[ 'label' => 'Schlecht', 'value' => 'ueber 0,25', 'note' => 'Die Seite fuehlt sich unsicher und unruhig an.' ],
		],
		'mistakes'         => [
			'Bilder, Formulare oder Embeds werden ohne feste Dimensionen in kritische Bereiche gesetzt.',
			'Consent-, Promo- oder Trust-Elemente werden spaet injiziert und verschieben CTAs nach unten.',
			'Instabilitaet wird als reines Designthema gelesen, obwohl sie direkte Conversion-Reibung erzeugt.',
		],
		'wgos_context'     => [
			'CLS betrifft nicht nur Performance, sondern konkrete Nachfragepfade. Wenn Buttons und Formulare springen, bricht Vertrauen im schlechtesten Moment weg.',
			'Deshalb ist die Metrik ein sauberer Glossar-Sub-Term unter dem Performance-Cluster, aber kein eigener Head Term.',
		],
		'primary_url_key'  => 'cwv',
		'primary_url_label'=> 'Core Web Vitals',
		'primary_url_reason' => 'CLS stuetzt die Cluster-URL, statt sie zu kopieren.',
		'related_primary_urls' => [
			[
				'key'    => 'cwv',
				'label'  => 'Core Web Vitals Cluster',
				'reason' => 'Setzt CLS in Beziehung zu Nutzererlebnis, Performance und Priorisierung.',
			],
			[
				'key'    => 'cro',
				'label'  => 'Conversion Rate Optimization',
				'reason' => 'Visuale Stabilitaet ist direkt conversion-relevant, auch wenn sie technisch gemessen wird.',
			],
		],
		'related_assets'   => [
			'cwv-speed-audit' => 'Hilft, die eigentlichen Shift-Ausloeser technisch sauber zu isolieren.',
		],
		'related_terms'    => [ 'inp', 'lcp', 'message-match' ],
		'seo_title'        => 'CLS: Definition, gute Werte und typische Ursachen | Haşim Üner',
		'seo_description'  => 'CLS einfach erklaert: Was Cumulative Layout Shift misst, welche Werte kritisch werden und warum visuelle Stabilitaet fuer Conversion mitzaehlt.',
	],
	'ttfb' => [
		'title'            => 'TTFB',
		'slug'             => 'ttfb',
		'status'           => 'publish',
		'core_area'        => 'Technisches Fundament',
		'index_policy'     => 'index',
		'excerpt'          => 'TTFB beschreibt, wie schnell der Server auf eine Anfrage erstmals antwortet.',
		'short_definition' => 'TTFB steht fuer Time to First Byte. Die Kennzahl zeigt, wann nach einer Anfrage das erste Byte vom Server zurueckkommt.',
		'why_it_matters'   => 'Ein hoher TTFB verlangsamt den gesamten Seitenstart. Selbst gutes Frontend-Tuning kann diesen Rueckstand nur begrenzt kompensieren.',
		'measurement'      => 'Entscheidend sind Hosting, Caching, Datenbanklast, Plugin-Overhead und externe Abhaengigkeiten vor dem ersten Antwortpaket.',
		'benchmarks'       => [
			[ 'label' => 'Gut', 'value' => 'deutlich unter 1 s', 'note' => 'Der Server antwortet frueh genug fuer einen stabilen Seitenstart.' ],
			[ 'label' => 'Warnsignal', 'value' => 'ab etwa 1 s', 'note' => 'Server- und Cache-Layer sollten genauer geprueft werden.' ],
		],
		'mistakes'         => [
			'Caching ist lueckenhaft oder greift nur auf Teilstrecken, waehrend dynamische Logik den Antwortstart verzoegert.',
			'Zu viele Plugins und externe Requests werden als Frontend-Thema behandelt, obwohl die Serverantwort schon zu spaet kommt.',
			'Teams verwechseln Gesamt-Ladezeit mit Server-Antwortzeit und priorisieren dadurch die falschen Hebel.',
		],
		'wgos_context'     => [
			'TTFB ist ein Fundament-Begriff. Wenn die erste Serverantwort zu spaet kommt, verlieren sowohl Sichtbarkeit als auch Conversion an Stabilitaet.',
			'Die Glossar-Seite erklaert den Begriff; die passende Analyse und der Audit zeigen, ob das Thema in Ihrer WordPress-Architektur wirklich Prioritaet hat.',
		],
		'primary_url_key'  => 'performance_analysis',
		'primary_url_label'=> 'Website Performance Analyse',
		'primary_url_reason' => 'TTFB ist ein technischer Sub-Term, der gut in den Audit- und Tool-Kontext ueberleitet.',
		'related_primary_urls' => [
			[
				'key'    => 'performance_analysis',
				'label'  => 'Website Performance Analyse',
				'reason' => 'Verbindet die Begriffsseite mit einem konkreten Einstieg in Messung und Bewertung.',
			],
			[
				'key'    => 'cwv',
				'label'  => 'Core Web Vitals Cluster',
				'reason' => 'Ordnet TTFB sauber in das groessere Performance-System ein.',
			],
		],
		'related_assets'   => [
			'cwv-speed-audit' => 'Zeigt, ob Server, Caching oder Theme-Logik den fruehen Antwortstart bremsen.',
		],
		'related_terms'    => [ 'inp', 'lcp', 'cls' ],
		'seo_title'        => 'TTFB: Definition, Ursachen und Einordnung | Haşim Üner',
		'seo_description'  => 'TTFB einfach erklaert: Was Time to First Byte bedeutet, welche Ursachen haeufig dahinterliegen und wie die Kennzahl in Performance-Checks einzuordnen ist.',
	],
	'canonical-url' => [
		'title'            => 'Canonical URL',
		'slug'             => 'canonical-url',
		'status'           => 'publish',
		'core_area'        => 'Sichtbarkeit',
		'index_policy'     => 'index',
		'excerpt'          => 'Die Canonical URL markiert die bevorzugte URL-Version eines Inhalts.',
		'short_definition' => 'Eine Canonical URL signalisiert Suchmaschinen, welche URL bei mehreren aehnlichen Versionen als bevorzugte Referenz gelten soll.',
		'why_it_matters'   => 'Ohne klare Canonical-Steuerung konkurrieren aehnliche URLs gegeneinander. Das kostet Signale, Klarheit und im schlimmsten Fall Rankings auf der falschen Seite.',
		'measurement'      => 'Relevant ist nicht nur der einzelne Tag im Head, sondern das Zusammenspiel aus interner Verlinkung, Sitemap, Redirects und tatsaechlicher Indexierung.',
		'mistakes'         => [
			'Canonical-Tags zeigen auf URLs, die intern kaum verlinkt oder per Redirect bereits ueberschrieben werden.',
			'Parameter-, Filter- oder Preview-Varianten bleiben crawlbar, obwohl die bevorzugte URL bereits feststeht.',
			'Mehrere Seiten zielen auf dieselbe Suchintention, waehrend Canonicals nur kosmetisch statt strukturell eingesetzt werden.',
		],
		'wgos_context'     => [
			'Im WGOS-System ist Canonical-Steuerung Teil der Primary-URL-Disziplin. Die eigentliche Arbeit besteht darin, Intent sauber auf die richtige Seite zu legen und Drift zu verhindern.',
			'Darum ist Canonical URL ein idealer Glossar-Sub-Term fuer technisches SEO, aber kein Ersatz fuer die Cluster- oder Angebotsseite selbst.',
		],
		'primary_url_key'  => 'seo',
		'primary_url_label'=> 'WordPress SEO Hannover',
		'primary_url_reason' => 'Der kommerzielle SEO-Intent bleibt auf der Cluster-Seite. Das Glossar klaert nur den Fachbegriff.',
		'related_primary_urls' => [
			[
				'key'    => 'seo',
				'label'  => 'WordPress SEO Hannover',
				'reason' => 'Fuehrt vom definitorischen Begriff zur eigentlichen SEO-Leistungsseite.',
			],
			[
				'key'    => 'wgos',
				'label'  => 'WGOS',
				'reason' => 'Zeigt, wie Canonical-Disziplin in die gesamte Seiten- und Intent-Architektur passt.',
			],
		],
		'related_assets'   => [
			'seitenrollen-mapping' => 'Hilft, doppelte Seitentypen und Intent-Ueberlagerungen frueh zu erkennen.',
			'roadmap-priorisierung' => 'Ordnet technische Konsolidierung gegen andere SEO- und Systembaustellen richtig ein.',
		],
		'related_terms'    => [ 'core-web-vitals', 'conversion-rate-optimization' ],
		'seo_title'        => 'Canonical URL: Definition und typische Fehler | Haşim Üner',
		'seo_description'  => 'Canonical URL erklaert: Was der Tag bewirkt, wo haeufige Fehler liegen und warum technische SEO mehr ist als nur ein einzelner Head-Tag.',
	],
	'utm-parameter' => [
		'title'            => 'UTM-Parameter',
		'slug'             => 'utm-parameter',
		'status'           => 'publish',
		'core_area'        => 'Messbarkeit',
		'index_policy'     => 'index',
		'excerpt'          => 'UTM-Parameter markieren Kampagnen-Traffic sauber, damit Quellen spaeter richtig lesbar sind.',
		'short_definition' => 'UTM-Parameter sind URL-Zusatzwerte, mit denen Kampagnenquelle, Medium, Kampagnenname und weitere Kontexte fuer Analytics kenntlich gemacht werden.',
		'why_it_matters'   => 'Ohne konsistente Parameter zerfaellt Kampagnen-Traffic in unklare Quellen. Dann werden Kanalvergleiche, Attribution und Reporting politisch statt belastbar.',
		'measurement'      => 'Wichtig ist nicht nur das Vorhandensein von UTM-Parametern, sondern ein einheitliches Namensschema ueber Teams, Ads, E-Mails und Retargeting hinweg.',
		'mistakes'         => [
			'Quelle, Medium und Kampagnenname werden frei erfunden und dadurch spaeter nicht mehr sauber auswertbar.',
			'Unterschiedliche Teams nutzen verschiedene Schreibweisen fuer denselben Kanal oder dieselbe Kampagne.',
			'Landing Pages sind kampagnenfaehig, aber die Datenbasis bleibt unscharf, weil Parameter und Events nicht zusammen gedacht werden.',
		],
		'wgos_context'     => [
			'UTM-Parameter gehoeren im WGOS nicht in eine isolierte Tracking-Ecke. Sie sind Teil einer Messbarkeitsschicht, die spaeter Kampagnen, Dashboards und Conversion-Entscheidungen tragefaehig macht.',
			'Die Glossar-Seite erklaert den Begriff. Das eigentliche Setup, die Datenlogik und die Governance bleiben auf der Tracking-Primary-URL.',
		],
		'primary_url_key'  => 'tracking',
		'primary_url_label'=> 'GA4 Tracking Setup',
		'primary_url_reason' => 'Der kommerzielle Setup-Intent bleibt auf der Tracking-Seite. Das Glossar klaert nur den Teilbegriff.',
		'related_primary_urls' => [
			[
				'key'    => 'tracking',
				'label'  => 'GA4 Tracking Setup',
				'reason' => 'Fuehrt von der Begriffsklaerung in die operative Implementierung.',
			],
			[
				'key'    => 'performance_marketing',
				'label'  => 'Performance Marketing',
				'reason' => 'UTM-Disziplin zahlt direkt auf kanalvergleichbare Paid-Daten ein.',
			],
		],
		'related_assets'   => [
			'tracking-audit' => 'Zeigt, ob Parameter, Events und Datenqualitaet heute ueberhaupt sauber zusammenspielen.',
		],
		'related_terms'    => [ 'owned-leads' ],
		'seo_title'        => 'UTM-Parameter: Definition, Aufbau und typische Fehler | Haşim Üner',
		'seo_description'  => 'UTM-Parameter einfach erklaert: Was sie leisten, welche Fehler haeufig passieren und warum saubere Kampagnenmarkierung fuer Reporting und Attribution entscheidend ist.',
	],
	'message-match' => [
		'title'            => 'Message Match',
		'slug'             => 'message-match',
		'status'           => 'publish',
		'core_area'        => 'Conversion',
		'index_policy'     => 'index',
		'excerpt'          => 'Message Match beschreibt, wie sauber Anzeige, Suchanfrage und Zielseite dieselbe Erwartung weiterfuehren.',
		'short_definition' => 'Message Match meint die Uebereinstimmung zwischen Einstiegssignal und Landing-Page-Botschaft. Nutzer sollen auf der Zielseite sofort wiedererkennen, dass sie richtig gelandet sind.',
		'why_it_matters'   => 'Wenn Anzeige, Suchsnippet oder CTA etwas versprechen, die Zielseite aber anders spricht, steigt Reibung schon im ersten Screen. Gute Message Matches verkuerzen den Weg zur naechsten Aktion.',
		'measurement'      => 'Pruefen Sie Headline, Hero, CTA, Proof und Formulierungen direkt gegen das Einstiegssignal. Entscheidend ist nicht Kreativitaet, sondern anschlussfaehige Fortsetzung.',
		'mistakes'         => [
			'Kampagnen und Landing Pages werden von verschiedenen Teams gebaut, ohne gemeinsame Nutzenbotschaft.',
			'Die Seite ist generisch, obwohl Anzeige oder Keyword sehr konkrete Erwartungen wecken.',
			'Proof, CTA und Headline bestaetigen den Einstieg nicht schnell genug und lassen Nutzer neu sortieren.',
		],
		'wgos_context'     => [
			'Message Match ist ein typischer Glossar-Sub-Term fuer CRO: hochrelevant, aber zu kleinteilig fuer die Head-Term-Seite selbst.',
			'Im WGOS verbindet der Begriff Positionierung, Landing-Page-Struktur und Kampagnenfaehigkeit zu einem gemeinsamen Conversion-Thema.',
		],
		'primary_url_key'  => 'cro',
		'primary_url_label'=> 'Conversion Rate Optimization',
		'primary_url_reason' => 'CRO bleibt der Head Term. Message Match ist das definitorische Mikrokonzept darunter.',
		'related_primary_urls' => [
			[
				'key'    => 'cro',
				'label'  => 'Conversion Rate Optimization',
				'reason' => 'Ordnet den Begriff in das groessere CRO-System ein.',
			],
			[
				'key'    => 'performance_marketing',
				'label'  => 'Performance Marketing',
				'reason' => 'Message Match wird besonders dort relevant, wo Kampagnen auf kaufnahe Zielseiten treffen.',
			],
		],
		'related_assets'   => [
			'landing-page-neu' => 'Wenn der Match strukturell nicht mehr zu retten ist, braucht es haeufig eine neue Zielseite statt nur Copy-Tuning.',
			'social-proof'     => 'Ergaenzt den Match dort, wo nach der Headline der Vertrauensbeweis fehlt.',
		],
		'related_terms'    => [ 'conversion-rate-optimization', 'owned-leads' ],
		'seo_title'        => 'Message Match: Definition und Bedeutung fuer CRO | Haşim Üner',
		'seo_description'  => 'Message Match einfach erklaert: Warum Anzeige, Suchintent und Landing Page dieselbe Erwartung weiterfuehren muessen und wie das auf CRO einzahlt.',
	],
	'owned-leads' => [
		'title'            => 'Owned Leads',
		'slug'             => 'owned-leads',
		'status'           => 'publish',
		'core_area'        => 'Strategie',
		'index_policy'     => 'index',
		'excerpt'          => 'Owned Leads sind Anfragen, die ueber eigene, kontrollierbare Kanaele und Systeme entstehen.',
		'short_definition' => 'Owned Leads sind Anfragen, die ueber die eigene Website, eigene Inhalte und eine kontrollierbare Nachfragearchitektur entstehen statt ausschliesslich ueber eingekaufte Reichweite.',
		'why_it_matters'   => 'Der Begriff schiebt die Diskussion weg von kurzfristigem Kampagnenoutput hin zu Systemkontrolle. Wer Leads nur mietet, bleibt von Plattformen, Preisen und Zwischenhaendlern abhaengig.',
		'measurement'      => 'Wichtig ist, welche Kanaele, Seiten und Signale Sie selbst kontrollieren: organische Einstiege, eigene Angebotsseiten, sauberes Tracking und wiederholbare Nachfragepfade.',
		'mistakes'         => [
			'Jede Anfrage wird gleich bewertet, obwohl die Abhaengigkeit vom ausloesenden Kanal komplett unterschiedlich sein kann.',
			'Teams investieren in Kampagnen, ohne die eigene Website als Nachfrage-System mitzuentwickeln.',
			'Owned Leads werden als Branding-Idee verstanden, nicht als messbare Architekturfrage aus Seiten, Tracking und Conversion.',
		],
		'wgos_context'     => [
			'Owned Leads ist bewusst ein Haşim-Lexikon-Begriff. Genau solche Begriffe differenzieren das Glossar von generischen SEO-Woerterbuechern und staerken gleichzeitig die WGOS-Pillar-Seite.',
			'Der Glossar-Eintrag erklaert die Logik. Die eigentliche Angebots- und Systemargumentation bleibt auf der WGOS-Primary-URL.',
		],
		'primary_url_key'  => 'wgos',
		'primary_url_label'=> 'WordPress Growth Operating System',
		'primary_url_reason' => 'Der strategische Head Term bleibt auf der WGOS-Pillar-Seite, waehrend das Glossar die interne Sprache schaerft.',
		'related_primary_urls' => [
			[
				'key'    => 'wgos',
				'label'  => 'WGOS',
				'reason' => 'Fuehrt vom Begriff direkt in die Systemlogik aus Fundament, Messbarkeit, Sichtbarkeit und Conversion.',
			],
			[
				'key'    => 'audit',
				'label'  => 'Growth Audit',
				'reason' => 'Ist der richtige Einstieg, wenn Owned Leads gewuenscht sind, das System aber noch keine saubere Reihenfolge hat.',
			],
		],
		'related_assets'   => [
			'growth-audit' => 'Hilft zu klaeren, welche Bremsen heute verhindern, dass aus der Website wirklich kontrollierbare Nachfrage wird.',
			'positionierungs-check' => 'Sichert, dass Owned Leads nicht nur technisch, sondern auch messaging-seitig tragfaehig werden.',
		],
		'related_terms'    => [ 'utm-parameter', 'message-match' ],
		'seo_title'        => 'Owned Leads: Bedeutung und strategische Einordnung | Haşim Üner',
		'seo_description'  => 'Owned Leads einfach erklaert: Was mit kontrollierbarer Nachfrage gemeint ist und warum der Begriff eng mit WGOS, Tracking und Angebotslogik zusammenhaengt.',
	],
	'core-web-vitals' => [
		'title'              => 'Core Web Vitals',
		'slug'               => 'core-web-vitals',
		'status'             => 'publish',
		'core_area'          => 'Technisches Fundament',
		'index_policy'       => 'alias',
		'excerpt'            => 'Alias-Eintrag: Der Head Term gehoert auf die Cluster-Seite, nicht auf eine zweite Glossar-URL.',
		'short_definition'   => 'Core Web Vitals ist im Glossar bewusst nur ein Alias auf die Primary URL.',
		'primary_url_key'    => 'cwv',
		'primary_url_label'  => 'Core Web Vitals Cluster',
		'primary_url_reason' => 'Head Term mit kommerzieller und strategischer Einordnung. Die Glossar-Rolle liegt auf INP, LCP, CLS und TTFB.',
		'seo_title'          => 'Core Web Vitals | Haşim Üner',
		'seo_description'    => 'Alias-Eintrag fuer Core Web Vitals. Der Begriff verweist bewusst auf die passende Cluster-Seite.',
	],
	'conversion-rate-optimization' => [
		'title'              => 'Conversion Rate Optimization',
		'slug'               => 'conversion-rate-optimization',
		'status'             => 'publish',
		'core_area'          => 'Conversion',
		'index_policy'       => 'alias',
		'excerpt'            => 'Alias-Eintrag: Der Head Term bleibt auf der Primary URL, das Glossar erklaert die Mikrokonzepte darunter.',
		'short_definition'   => 'Conversion Rate Optimization ist im Glossar bewusst nur als Alias vorhanden.',
		'primary_url_key'    => 'cro',
		'primary_url_label'  => 'Conversion Rate Optimization',
		'primary_url_reason' => 'Der Head Term soll nicht durch eine zweite definitorische URL kannibalisiert werden. Das Glossar konzentriert sich auf Message Match, CTA-Hierarchie und aehnliche Sub-Terms.',
		'seo_title'          => 'Conversion Rate Optimization | Haşim Üner',
		'seo_description'    => 'Alias-Eintrag fuer Conversion Rate Optimization. Der Begriff verweist bewusst auf die passende Cluster-Seite.',
	],
];
