name: Deploy to Raidboxes

# Wird ausgelöst bei Push zum main Branch
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Manueller Start möglich

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Deploy via SFTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        protocol: sftp
        local-dir: ./
        server-dir: /home/wp/disk/wordpress/wp-content/themes/blocksy-child/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.DS_Store
          **/.github/**
