name: Deploy Theme

on:
  push:
    branches: [ main ]
    paths:
      - 'blocksy-child/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: ssh-action/sftp-upload@v2
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: 22
          remote_path: /www/wp-content/themes/blocksy-child/
          local_path: ./blocksy-child/
