name: Deploy Theme

on:
  push:
    branches: [main]
    paths:
      - 'blocksy-child/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'RB606538'
          server: 'sftp.raidboxes.de'
          password: ${{ secrets.FTP_PASS }}
          local_path: './blocksy-child/'
          remote_path: '/www/wp-content/themes/blocksy-child/'
          port: 22
