name: Deploy to Raidboxes

# Wird ausgelöst bei Push zum main Branch
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Manueller Start möglich

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Deploy via Pure SFTP
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}  
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        uploads: |
          ./ => /248304_hasim___ner/wordpress/wp-content/themes/blocksy-child/
