name: Deploy Theme
on:
  push:
    branches: [ main ]
    paths:
      - 'blocksy-child/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SFTP (Raidboxes)
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_HOST }}          # z.B. sftp.raidboxes.de
          port: 22
          username: ${{ secrets.FTP_USER }}        # z.B. RB606538
          password: ${{ secrets.FTP_PASS }}        # Dein RB-Dashboard-Passwort
          local_path: ./blocksy-child/*            # Dein Child-Theme lokal
          remote_path: wp-content/themes/blocksy-child/  # Zielordner auf Raidboxes
