name: Deploy Theme

on:
  push:
    branches: [main]
    paths:
      - 'blocksy-child/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Remove git files
        run: |
          rm -rf ./blocksy-child/.git
          rm -rf ./blocksy-child/.github

      - name: Deploy via RSYNC
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./blocksy-child/
          remote_path: /www/wp-content/themes/blocksy-child/
          remote_host: sftp.raidboxes.de
          remote_user: RB606538
          remote_key: ${{ secrets.FTP_PASS }}
