name: Deploy Theme

on:
  push:
    branches: [ main ]
    paths:
      - 'blocksy-child/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: sftp.raidboxes.de
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          port: 22 # Standard-SFTP-Port, falls nicht explizit anders konfiguriert
          protocol: sftp
          server-dir: /www/wp-content/themes/blocksy-child/
          local-dir: ./blocksy-child/
          dangerous-clean-slate: true # Nutze dies, um alle Dateien zu synchronisieren.
