name: Deploy to Raidboxes (Final)

on:
  push:
    branches: [main]
    paths:
      - 'blocksy-child/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: sftp.raidboxes.de
          username: RB606538
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "--- Verbindung erfolgreich ---"
            cd /www/wp-content/themes/
            rsync -avzr --delete ${{ github.workspace }}/blocksy-child/ ./blocksy-child/
            echo "--- Deployment erfolgreich abgeschlossen ---"