name: Deploy Theme

on:
  push:
    branches: [main]
    paths:
      - 'blocksy-child/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Deploy via SFTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: './blocksy-child/'
          server-dir: '/www/wp-content/themes/blocksy-child/'
