name: Deploy Theme (SSH)

on:
  push:
    branches: [ main ]
    paths:
      - 'blocksy-child/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy via rsync over SSH
        run: |
          rsync -az --delete \
            -e "ssh -i ~/.ssh/id_rsa -p 22 -o StrictHostKeyChecking=yes" \
            ./blocksy-child/ \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:www/wp-content/themes/blocksy-child/"
