name: Deploy Theme

on:
  push:
    branches: [main]
    paths:
      - 'blocksy-child/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List files
        run: ls -la

      - name: Create remote directory
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: sftp.raidboxes.de
          username: RB606538
          password: ${{ secrets.FTP_PASS }}
          port: 22
          script: |
            mkdir -p /www/wp-content/themes/blocksy-child/
            chmod 755 /www/wp-content/themes/blocksy-child/

      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: sftp.raidboxes.de
          username: RB606538
          password: ${{ secrets.FTP_PASS }}
          port: 22
          source: './blocksy-child/*'
          target: '/www/wp-content/themes/blocksy-child/'
