name: SSH Connection Test

on:
  push:
    branches: [main]

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Connection to Raidboxes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: sftp.raidboxes.de
          username: RB606538
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "--- VERBINDUNG ERFOLGREICH! ---"
            echo "--- Inhalt des Home-Verzeichnisses: ---"
            ls -la
            echo "--- Inhalt von wp-content: ---"
            ls -la /www/wp-content