name: Deploy Theme via SSH/RSYNC

on:
  push:
    branches: [main]
    paths:
      - 'blocksy-child/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Theme to Server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --delete
          path: ./blocksy-child/
          remote_path: /www/wp-content/themes/blocksy-child/
          remote_host: sftp.raidboxes.de
          remote_user: RB606538
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
