name: Deploy Theme
on:
  push:
    branches: [ main ]
    paths:
      - 'blocksy-child/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SFTP (git-ftp)
        uses: dfedde/git-ftp-action@releases/v4
        with:
          url: sftp://sftp.raidboxes.de/www/wp-content/themes/blocksy-child
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          syncroot: blocksy-child
