name: Deploy Theme

on:
  push:
    branches: [main]
    paths:
      - 'blocksy-child/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SCP
        uses: appleboy/scp-action@v0.1.3
        with:
          host: sftp.raidboxes.de
          username: RB606538
          password: ${{ secrets.FTP_PASS }}
          port: 22
          source: './blocksy-child/'
          target: '/www/wp-content/themes/'
          scp_options: '-r'
