- name: Deploy via SFTP
  uses: wlixcc/SFTP-Deploy-Action@v1.2.4
  with:
    username: ${{ secrets.FTP_USER }}
    server: ${{ secrets.FTP_HOST }}
    password: ${{ secrets.FTP_PASS }}
    local_path: './blocksy-child/*'
    remote_path: '/www/wp-content/themes/blocksy-child/'
