name: Deploy to Raidboxes

# Wird ausgelöst bei Push zum main Branch
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Manueller Start möglich

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Deploy via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        local_path: './*'
        remote_path: '/'
        sftpArgs: '-o ConnectTimeout=5'
